import { ref, computed } from 'vue'
import { defineStore } from 'pinia'

export const useStore = defineStore('store', {
	state: () => ({
		bg: 'bg-white',
		modal: false,
		feedback: false,
		comp: 'Contacts',
		lang: 'ru',
		isLoggedin: false,
		langProp: {
	
			 'ru': {
			 
			 	'lang': 'Язык',
				'catalogue': 'Каталог',
				'about': 'О нас',
				'blog': 'Блог',
				'contacts': 'Контакты',
				'entrance': 'Вход',
				'registeration': 'Регистрация',
				'loginWithGoogle':'Вход через Google',
				'enterEmail':'Введите Email',
				'enterPassword': 'Введите пароль',
				'password': 'Пароль',
				'confirmThePassword': 'Подтвердите пароль',
				'username': 'Имя пользователя',
				'minimumNumberOfSymbols': 'Минимальное кол-во символов',
				'passwordMismatch': 'Пароли не совпадают',
				'toComeIn': 'Войти',
				'doYouAlreadyHaveAnAccount': 'У Вас уже есть аккаунт?',
				'forgotYourPassword': 'Забыли пароль?',
				'dontHaveAnAccountYet': 'У Вас еще нет аккаунта?',
				'create': 'Создать',
				'aboutUs': 'О нас',
				'aboutUsP1': 'Мы рады приветствовать Вас на нашем семейном производстве экологически чистых продуктов',
				'aboutUsP2':'Наше небольшое семейное производство берет свое начало в далеком 1996 году, а началось все с того, что наш папа решил завести несколько пчелиных семей и начал постигать основы общения с пчелами, изучать их нрав и поведение. Изначально пчел у нас было не много, всего 16 семей Среднерусской породы, за тем по мере углубления в изучение пчеловодства мы экспериментировали и заводили другие породы пчел:',
				'aboutUsP3': 'в 2000 году мы заводили Карпатскую породу пчел, порядка 15 семей, в 2014 перешли на породу Карника и увеличили количество семей уже до 40, а к 2020 году увеличили количество семей этой породы до 235. С 2022 года мы оставили 110 семей пород Бакфаст и Карника.',
				'aboutUsP4': 'Экологически чистое место расположение нашей пасеки в высокогорье Джалал-Абадской области обеспечивает высокое качество продукта, чистый горный воздух, обширные луга с разными травами, кристально-чистая вода горных рек ледникового происхождения, все это делает наш мед неповторимым по составу и качеству.',
				'aboutUsP5': 'Приобретая нашу продукцию Вы обеспечиваете здоровье и долголетие Вас и Вашей семьи!',
				'blogP1': 'Интересные факты про мед',
				'blogP2': 'Мед — очень полезный продукт питания. Настоящий мед делают только пчелы. Благодаря большому содержанию полезных веществ этот продукт обладает целебными свойствами. Самые интересные факты о мёде — в этой статье. В 1985 году перуанские наркодиллеры выпускали пчел прямо на поля с цветущим коки. Насекомые собрали наркотический мед, который был конфискован на границе. Для изготовления литра меда пчелы собирают 2,5 литра нектара. Испанцы добавляют мед к искусственному питанию детей, болеющих желтухой или болезнями крови.',
				'blogP3': 'Цветочный мед',
				'blogP4': 'Сложность цветочного медав том, что привести его к какой-то одной характеристике по внешнему виду невозможно. Цвет и запах зависит от того, где и с каких растений он был собран. Наиболее часто встречающиеся разновидности по цвету - светло-желтый или оранжевый мед. Также на рынке можно встретить янтарные оттенки меда, золотистые, темно-коричневые. Чуть реже встречается мед зеленоватого оттенка. Что касается запаха, то здесь обязательно превалируют цветочные ароматы, часто слышатся фруктовые нотки. Есть включения сладкого или пряного аромата. На вкус цветочный мед - очень деликатный, нежный, послевкусие - продолжительное. В меде чувствуется приятный травяной привкус.',
				'feedback': 'Обратная связь',
				'address': 'Адрес:',
				'kyrgyzstan': 'Кыргызстан',
				'street': 'ул.Киевская 77',
				'telephone': 'Телефон:',
				'telephone_1': 'Телефон',
				'socialNetworks': 'Соц. сети:',
				'contactUs': 'Свяжитесь с нами',
				'yourName' : 'Ваше Имя',
				'message': 'Сообщение',
				'send': 'Отправить',
				'reset': 'Сбросить',
				'personalArea': 'Личный кабинет',
				'myOrders': 'Мои заказы',
				'settings': 'Настройки',

			},
			 'en':{
			 
			 	'lang': 'Lang',
				'catalogue': 'Products',
				'about': 'About us',
				'blog': 'Blog',
				'contacts': 'Contacts',
				'entrance': 'Entrance',
				'registeration': 'Registration',
				'loginWithGoogle': 'Login with Google',
				'enterEmail':'Enter Email',
				'enterPassword': 'Enter password',
				'password': 'Password',
				'confirmThePassword': 'Confirm the password',
				'username': 'Username',
				'minimumNumberOfSymbols': 'Minimum number of symbols',
				'passwordMismatch': 'Password mismatch',
				'toComeIn': 'To come in',
				'doYouAlreadyHaveAnAccount': 'Do you already have an account?',
				'forgotYourPassword': 'Forgot your password?',
				'dontHaveAnAccountYet': 'Do not have an account yet?',
				'create': 'Create',
				'aboutUs': 'About Us',
				'aboutUsP1': 'We are pleased to welcome you to our family-run production of organic products',
				'aboutUsP2':'Our small family business dates back to 1996, and it all started with the fact that our dad decided to start several bee colonies and began to comprehend the basics of communication with bees, to study their temper and behavior. Initially, we did not have many bees, only 16 families of the Central Russian breed, then, as we deepened in studying beekeeping, we experimented and started other breeds of bees:',
				'aboutUsP3': 'in 2000 we started the Carpathian breed of bees, about 15 families, in 2014 we switched to the Karnika breed and increased the number of families is already up to 40, and by 2020 the number of families of this breed has been increased to 235. Since 2022, we have left 110 families of Buckfast and Karnika breeds.',
				'aboutUsP4': 'An ecologically clean place, the location of our apiary in the highlands of the Jalal-Abad region provides high product quality, clean mountain air, vast meadows with various herbs, crystal clear mountain water rivers of glacial origin, all this makes our honey unique in composition and quality.',
				'aboutUsP5': 'By purchasing our products you ensure the health and longevity of you and your family!',
				'blogP1': 'Interesting facts about honey',
				'blogP2': 'Honey is a very useful food product. Only bees make real honey. Thanks to the great content nutrients this product has healing properties. The most interesting facts about honey - in this article. In 1985, Peruvian drug dealers released bees into coca fields. Insects collected narcotic honey that was confiscated at the border. To make a liter of honey, bees collect 2.5 liters of nectar. The Spaniards add honey to the artificial nutrition of children suffering from jaundice or blood diseases.',
				'blogP3': 'Flower honey',
				'blogP4': 'The complexity of flower honey is that it is impossible to bring it to any one characteristic in appearance. The color and smell depends on where and from which plants it was collected. The most common varieties in color are light yellow or orange honey. Also on the market you can find amber shades of honey, golden, dark brown. Slightly less common is honey of a greenish hue. As for the smell, floral aromas definitely prevail here, fruity notes are often heard. There are inclusions of a sweet or spicy aroma. The taste of flower honey is very delicate, delicate, the aftertaste is long. Honey has a pleasant herbal flavor.',
				'feedback': 'Feedback',
				'address': 'Address:',
				'kyrgyzstan': 'Kyrgyzstan',
				'street': 'Kievskaya street 77',
				'telephone': 'Telephone:',
				'socialNetworks': 'Social networks:',
				'contactUs': 'Contact us',
				'yourName' : 'Your name',
				'telephone_1': 'Telephone',
				'message': 'Message',
				'send': 'Send',
				'reset': 'Reset',
				'personalArea': 'Personal Area',
				'myOrders': 'My orders',
				'settings': 'Settings',
				
			},
			 'kg':{
			 
			 	'lang': 'Тил',
				'catalogue': 'Каталог',
				'about': 'Биз жөнүндө',
				'blog': 'Блог',
				'contacts': 'Байланыштар',
				'entrance': 'Кире бериш',
				'registeration': 'Каттоо',
				'loginWithGoogle':'Google менен кириңиз',
				'enterEmail': 'Электрондук почтаны киргизиңиз',
				'enterPassword': 'Сырсөздү киргизиңиз',
				'password': 'Купуя сөз',
				'confirmThePassword': 'Сырсөздү ырастаңыз',
				'username':'Колдонуучунун аты',
				'minimumNumberOfSymbols': 'Символдордун минималдуу саны',
				'passwordMismatch': 'Сырсөз дал келбейт',
				'toComeIn': 'Кирүү үчүн',
				'doYouAlreadyHaveAnAccount': 'Сиздин аккаунтуңуз барбы?',
				'forgotYourPassword': 'Сыр сөзүңүздү унуттуңузбу?',
				'dontHaveAnAccountYet': 'Азырынча аккаунтуңуз жокпу?',
				'create': 'Түзүү',
				'aboutUs': 'Биз жөнүндө',
				'aboutUsP1': 'Сизди биздин үй-бүлөбүздүн органикалык өндүрүшүндө тосуп алууга кубанычтабыз	буюмдар',
				'aboutUsP2':'Биздин чакан үй-бүлөлүк бизнесибиз 1996-жылдан бери башталган жана анын баары биздин ата бир нече аары колонияларын түзүүнү чечти жана аарылар менен баарлашуунун негиздерин түшүнө баштады, алардын мүнөзүн жана мүнөзүн изилдей баштады. жүрүм-турум. Адегенде бизде аарылар көп болгон эмес, болгону 16 үй-бүлө Борбордук орус породасындагы, андан кийин тереңдеген сайын окуп жатат аарычылык, биз эксперимент жүргүзүп, аарылардын башка породаларын баштадык:',
				'aboutUsP3': '2000-жылы аарылардын Карпат породасын, 15ке жакын үй-бүлөнү, 2014-жылы Карника породасын жана көбөйдү үй-бүлөлөрдүн саны 40ка жетти, ал эми 2020-жылга чейин бул породадагы үй-бүлөлөрдүн саны 235ке чейин көбөйтүлдү. 2022-жылдан бери биз Бакфаст жана Карника породаларынын 110 үй-бүлөсүн калтырдык.',
				'aboutUsP4': 'Экологиялык жактан таза жер, биздин бал челектин Жалал-Абад облусунун бийик тоолуу аймагында жайгашканы бийик продукциянын сапаты, таза тоонун абасы, ар кандай чөптөр өскөн кең шалбаалар, тунук тоо суулары дарыялар мөңгүдөн келип чыккан, мунун баары биздин балды курамы жана сапаты боюнча уникалдуу кылат.',
				'aboutUsP5': 'Биздин продукцияларды сатып алуу менен сиз өзүңүздүн жана үй-бүлөңүздүн ден соолугун жана узак өмүрүн камсыздайсыз!',
				'blogP1': 'Бал жөнүндө кызыктуу фактылар',
				'blogP2': 'Бал абдан пайдалуу тамак-аш продуктусу. Чыныгы балды аарылар гана жасайт. Улууга рахмат мазмун бул продукт дарылык касиетке ээ. Бал жөнүндө эң кызыктуу фактылар - жылы бул макала. 1985-жылы Перулук баңгизат сатуучулар аарыларды кока талааларына кое беришкен. Курт-кумурскалар чогултулган чек арадан алынган наркотикалык бал. Бир литр бал алуу үчүн аарылар 2,5 литр шире чогултат. Испаниялыктар сарык же кан оорулары менен ооруган балдардын жасалма тамактануусуна бал кошуп беришет.',
				'blogP3': 'Гүл бал',
				'blogP4': 'Гүл балынын татаалдыгы, аны сырткы көрүнүшү боюнча кандайдыр бир өзгөчөлүккө алып келүү мүмкүн эмес. Түсү жана жыты анын кайдан жана кайсы өсүмдүктөрдөн чогултулганына жараша болот. түсү көп таралган сорттору ачык сары же кызгылт сары бал болуп саналат. Ошондой эле рынокто бал, алтын, кара күрөң янтарь көлөкөлөрүн таба аласыз. Бир аз таралган жашыл түстөгү бал. Жытка келсек, бул жерде сөзсүз түрдө гүл жыттары басымдуулук кылат, мөмөлүү ноталар көп угулат. таттуу же ачуу жыпар жыттуу кошулмалар бар. Гүлдүн балынын даамы өтө назик, назик, даамы узун. Балдын жагымдуу чөп даамы бар.',
				'feedback': 'Кайра Байланыш',
				'address': 'Дарек:',
				'kyrgyzstan': 'Кыргызстан',
				'street': 'Киев көчөсү 77',
				'telephone': 'Телефон:',
				'socialNetworks': 'Социалдык тармактар:',
				'contactUs': 'Биз менен байланыш',
				'yourName' : 'Сиздин атыңыз',
				'telephone_1': 'Телефон',
				'message': 'Кабар',
				'send': 'Жөнөтүү',
				'reset': 'Калыбына келтирүү',
				'personalArea': 'Жеке бөлмө',
				'myOrders': 'Менин заказдарым',
				'settings': 'Орнотуулар',
								
			}
		}
	}),
})
